/**
 * PATH-shim installer. For every detected shim-safe agent binary we write a
 * tiny bash script under ${WRAPBOX_HOME}/shims/<name> that re-exec's the real
 * binary through `wrapboxd run --agent <id> --net proxy`.
 *
 * The user is expected to prepend ${WRAPBOX_HOME}/shims to PATH. The shim
 * resolves the real binary via WRAPBOX_ORIGINAL_PATH (captured at wrap time)
 * so we never re-invoke ourselves.
 */
import fs from "node:fs";
import path from "node:path";
import { sha256hex } from "./canonical.js";
import { PATHS } from "./config.js";
import { detectAgents, shimTargets } from "./discover.js";
import { loadState, saveState } from "./receipts.js";

export const SHIMS_DIR = path.join(PATHS.home, "shims");

/**
 * Network mode baked into a shim.
 *
 * "proxy" is the strongest: the sandbox permits only loopback egress to the
 * local policy proxy, so every destination is checked. It costs compatibility —
 * a client that ignores HTTP_PROXY/HTTPS_PROXY (Node's undici does by default)
 * gets no network at all rather than a proxied one, which looks like a broken
 * agent. "on" keeps the kernel file rules and leaves egress alone.
 */
export type ShimNetMode = "proxy" | "on" | "off";

function shimContents(registryId: string, binName: string, net: ShimNetMode): string {
  // NOTE: /usr/local/bin/wrapboxd is the documented install path. Callers
  // testing without a global install can set WRAPBOXD_BIN to point elsewhere;
  // the shim honours that override if present at wrap time.
  const bin = process.env.WRAPBOXD_BIN || "/usr/local/bin/wrapboxd";
  return `#!/bin/sh
# Wrapbox shim for ${binName}. Do not edit — regenerated by \`wrapboxd wrap\`.
set -e
REAL="$(PATH="$WRAPBOX_ORIGINAL_PATH" command -v ${binName} 2>/dev/null || true)"
if [ -z "$REAL" ] || [ "$REAL" = "$0" ]; then
  echo "wrapboxd shim: cannot resolve real ${binName} — is it installed on PATH?" >&2
  exit 127
fi
exec ${bin} run --agent ${registryId} --net ${net} -- "$REAL" "$@"
`;
}

export interface WrapResult {
  installed: { registryId: string; binName: string; path: string; sha256: string }[];
  removed: string[];
  hint: string;
}

function captureOriginalPath(): string {
  // Whatever the user's PATH is right now, minus our shim dir if it's already
  // in there. This gets stamped into state.json so shims can bypass us.
  const parts = (process.env.PATH || "").split(":").filter((d) => d && d !== SHIMS_DIR);
  return parts.join(":");
}

export async function installShims(only?: string[], net: ShimNetMode = "on"): Promise<WrapResult> {
  fs.mkdirSync(SHIMS_DIR, { recursive: true });
  const sightings = await detectAgents();
  const targets = shimTargets(sightings).filter((t) => !only || only.includes(t.entry.id));

  const state = loadState();
  const shims: Record<string, { registryId: string; sha256: string }> =
    (state as any).shims ?? {};

  const installed: WrapResult["installed"] = [];
  for (const t of targets) {
    for (const binName of t.binNames) {
      const p = path.join(SHIMS_DIR, binName);
      const contents = shimContents(t.entry.id, binName, net);
      fs.writeFileSync(p, contents, { mode: 0o755 });
      fs.chmodSync(p, 0o755);
      const sha = sha256hex(contents);
      installed.push({ registryId: t.entry.id, binName, path: p, sha256: sha });
      shims[binName] = { registryId: t.entry.id, sha256: sha };
    }
  }

  const originalPath = (state as any).original_path || captureOriginalPath();
  saveState({ ...state, shims, original_path: originalPath } as any);

  const hint = `Add ${SHIMS_DIR} to the FRONT of your PATH:\n` +
    `  export WRAPBOX_ORIGINAL_PATH="$PATH"\n` +
    `  export PATH="${SHIMS_DIR}:$PATH"\n` +
    `(append the above two lines to ~/.zshrc — wrapboxd will NOT modify it for you.)`;

  return { installed, removed: [], hint };
}

export function uninstallShims(): WrapResult {
  // Only remove shims we installed (tracked in state.json with their sha256).
  // A stray file in SHIMS_DIR that we did not create is left alone — silently
  // deleting it would be tampering by the daemon itself.
  const removed: string[] = [];
  const state = loadState();
  const shims: Record<string, { registryId: string; sha256: string }> = (state as any).shims ?? {};
  for (const [binName, meta] of Object.entries(shims)) {
    const p = path.join(SHIMS_DIR, binName);
    let actual = "";
    try { actual = sha256hex(fs.readFileSync(p, "utf-8")); } catch { /* already gone */ continue; }
    if (actual !== meta.sha256) continue; // drifted — leave for the operator to inspect
    try { fs.unlinkSync(p); removed.push(p); } catch { /* skip */ }
  }
  saveState({ ...state, shims: {} } as any);
  return { installed: [], removed, hint: "" };
}

export interface ShimTamperReport {
  drifted: { binName: string; path: string; expected: string; actual: string }[];
  missing: string[];
}

export function checkShimTamper(): ShimTamperReport {
  const state = loadState();
  const shims: Record<string, { registryId: string; sha256: string }> = (state as any).shims ?? {};
  const drifted: ShimTamperReport["drifted"] = [];
  const missing: string[] = [];
  for (const [binName, meta] of Object.entries(shims)) {
    const p = path.join(SHIMS_DIR, binName);
    let contents = "";
    try { contents = fs.readFileSync(p, "utf-8"); } catch { missing.push(p); continue; }
    const actual = sha256hex(contents);
    if (actual !== meta.sha256) drifted.push({ binName, path: p, expected: meta.sha256, actual });
  }
  return { drifted, missing };
}
