import type { TourCase } from "../types";

// Alex's team runs a ten-step agent job; only the production deploy waits for Alex's yes.
const c: TourCase = {
  id: "task-deploy",
  order: 55,
  persona: { userId: "u-alex", name: "Alex Morgan", role: "Engineering Manager" },
  title: "Approve one risky step mid-job",
  goal: "Daniel's coding agent is fixing a checkout bug, and Alex decides whether the fix may go to production.",
  outcome: "The safe steps ran on their own, the deploy waited for Alex's yes, and the whole job finished with that approval on record.",
  start: "tasks",
  poster: 3,
  steps: [
    {
      target: { selector: ".ecard", text: "Fix checkout and deploy" },
      title: "A coding job with limits",
      body: "Daniel asks Claude Code, an AI coding agent, to fix a checkout bug and ship it. Shipping to production needs a yes, and Alex is the approver.",
      say: "So here's the job: Daniel asks Claude Code, an AI coding agent, to fix a checkout bug and ship it. Shipping to production needs a yes, and Alex is the approver.",
    },
    {
      target: { within: ".ecard", selector: "button", text: "Start" },
      action: "click",
      title: "Start with least privilege",
      body: "One click gives the agent a short-lived, least-privilege permission slip: only what this job needs, for 30 minutes. Anything on the Forbidden list, like production, needs a person's yes.",
      say: "One click starts the agent with a short-lived, least-privilege permission slip: only what this job needs, for thirty minutes. Anything on the Forbidden list, like production, needs a person's yes.",
      waitFor: { selector: ".grid.g2", text: "Forbidden" },
      placement: "top",
    },
    {
      target: ".scroll-thin",
      title: "Every step is checked first",
      body: "Steps 1 to 5 were routine, so ALLOW: they simply ran. Step 6 deploys to production, so REVIEW: it is parked, waiting for a person's yes.",
      say: "Okay, every step gets checked first. Steps one to five were routine, so they just ran, but step six deploys to production, so it's parked, waiting for a person's yes.",
      placement: "top",
    },
    {
      target: { selector: ".scroll-thin > div", text: "Verify production health" },
      action: "hover",
      title: "Safe work keeps going",
      body: "Steps 7 to 9 don't need the deploy, so they finished anyway. Only step 10, the production health check, waits for it.",
      say: "Meanwhile, steps seven to nine don't need the deploy, so they finished anyway. Only step ten, the production health check, waits for it.",
      waitFor: ".scroll-thin",
      placement: "top",
    },
    {
      target: { selector: "a", text: "Review Center" },
      action: "click",
      title: "Sent to the right person",
      body: "The task names who must decide: Alex, never Daniel, who asked for the change. The link opens the Review Center, where only held actions wait.",
      say: "The task names who has to decide: Alex, never Daniel, who asked for the change. This link opens the Review Center, where only held actions wait.",
      waitFor: { selector: ".ecard-fields", text: "Decides" },
      pad: 10,
      placement: "top",
    },
    {
      target: { selector: ".grid.g3 > div", text: "Production deployments require SRE approval" },
      title: "Why the deploy is waiting",
      body: "A company rule held it: production deploys need sign-off from site reliability (SRE). Alex is the approver this job names for that sign-off.",
      say: "A company rule held it: production deploys need sign-off from site reliability. And for this job, Alex is the named approver for that sign-off.",
      pad: 10,
    },
    {
      target: { selector: "button", text: "Approve scoped" },
      action: "click",
      title: "Yes, for this job only",
      body: "Approve scoped: yes to the deploy, and this job alone may use AWS Production until it ends. The queue empties; the health check needs no second yes.",
      say: "Alex picks Approve scoped: yes to the deploy, and only this job can use AWS Production until it ends. The queue empties, and the health check needs no second yes.",
      waitFor: { selector: ".card", text: "Nothing waiting" },
    },
    {
      target: { selector: ".rail-item", text: "Tasks" },
      action: "click",
      title: "The job picked up by itself",
      body: "Back in Tasks, nothing is parked and one job is completed. The moment Alex said yes, the task resumed without anyone restarting it.",
      say: "Nice. Back in Tasks, nothing's parked and one job is completed. The moment Alex said yes, the task picked up again without anyone restarting it.",
      waitFor: { selector: ".card", text: "finished within envelope" },
    },
    {
      target: { selector: ".tab", text: "Finished" },
      action: "click",
      title: "The extra access, on record",
      body: "The job is now under Finished. Alex's scoped yes is written into it: AWS Production, valid for this task only, with Alex's name on it.",
      say: "The job's now under Finished, and Alex's scoped yes is written right into it: AWS Production, valid for this task only, with Alex's name on it.",
      waitFor: { selector: ".card .card", text: "Extra scope approved" },
    },
    {
      target: { selector: ".scroll-thin > div", text: "Verify production health" },
      action: "hover",
      title: "All ten steps done",
      body: "The job is COMPLETED. Routine steps ran on their own, the deploy waited for Alex's yes, and the health check ran under that same approval.",
      say: "All ten steps are done. Routine ones ran on their own, the deploy and health check ran on Alex's single yes, and that approval stays on record.",
      waitFor: ".scroll-thin",
      placement: "top",
    },
  ],
};
export default c;
